#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
# Fyren Install Script
# https://fyren.dev
# ─────────────────────────────────────────────

COMPOSE_URL="https://raw.githubusercontent.com/fyrendev/fyren/main/docker-compose.images.yml"

# ─── Colors ───

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m' # No Color

# ─── Banner ───

banner() {
  echo ""
  echo -e "${CYAN}${BOLD}"
  echo "    ╔═╗┬ ┬┬─┐┌─┐┌┐┌"
  echo "    ╠╣ └┬┘├┬┘├┤ │││"
  echo "    ╚   ┴ ┴└─└─┘┘└┘"
  echo -e "${NC}"
  echo -e "  ${DIM}The open source lighthouse for your services${NC}"
  echo ""
}

# ─── Helpers ───

info() {
  echo -e "  ${CYAN}>${NC} $1"
}

success() {
  echo -e "  ${GREEN}✓${NC} $1"
}

warn() {
  echo -e "  ${YELLOW}!${NC} $1"
}

error() {
  echo -e "  ${RED}✗${NC} $1"
}

# ─── Prerequisites ───

check_prerequisites() {
  local missing=0

  for cmd in docker openssl curl; do
    if ! command -v "$cmd" &>/dev/null; then
      error "$cmd is not installed"
      missing=1
    else
      success "$cmd found"
    fi
  done

  if ! docker compose version &>/dev/null; then
    error "docker compose plugin is not installed"
    missing=1
  else
    success "docker compose found"
  fi

  if [ "$missing" -eq 1 ]; then
    echo ""
    error "Please install the missing prerequisites and try again."
    exit 1
  fi
}

# ─── Prompts ───

prompt_domain() {
  while true; do
    echo ""
    echo -e "  ${BOLD}Domain${NC}"
    echo -e "  ${DIM}Where will Fyren be hosted? (e.g. status.example.com)${NC}"
    printf "  > "
    read -r APP_DOMAIN

    # Strip protocol prefix if provided
    APP_DOMAIN="${APP_DOMAIN#http://}"
    APP_DOMAIN="${APP_DOMAIN#https://}"
    # Strip trailing slash
    APP_DOMAIN="${APP_DOMAIN%/}"

    if [ -z "$APP_DOMAIN" ]; then
      warn "Domain cannot be empty"
      continue
    fi

    if [[ "$APP_DOMAIN" == *" "* ]]; then
      warn "Domain cannot contain spaces"
      continue
    fi

    if [[ ! "$APP_DOMAIN" == *.* ]]; then
      warn "Please enter a valid domain (e.g. status.example.com)"
      continue
    fi

    break
  done
}

prompt_email() {
  while true; do
    echo ""
    echo -e "  ${BOLD}ACME Email${NC}"
    echo -e "  ${DIM}Email for Let's Encrypt SSL certificates${NC}"
    printf "  > "
    read -r ACME_EMAIL

    if [ -z "$ACME_EMAIL" ]; then
      warn "Email cannot be empty"
      continue
    fi

    if [[ ! "$ACME_EMAIL" == *@*.* ]]; then
      warn "Please enter a valid email address"
      continue
    fi

    break
  done
}

# ─── Generate Secrets ───

generate_secrets() {
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  REDIS_PASSWORD=$(openssl rand -hex 16)
  BETTER_AUTH_SECRET=$(openssl rand -base64 32)
}

# ─── Download Compose File ───

download_compose() {
  info "Downloading docker-compose.yml..."
  if ! curl -fsSL "$COMPOSE_URL" -o docker-compose.yml; then
    error "Failed to download docker-compose.yml"
    exit 1
  fi
  success "docker-compose.yml downloaded"
}

# ─── Write .env ───

write_env() {
  cat > .env <<EOF
# Fyren Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ─── Domain ───
APP_DOMAIN=$APP_DOMAIN
APP_URL=https://$APP_DOMAIN
ACME_EMAIL=$ACME_EMAIL

# ─── Database ───
POSTGRES_DB=fyren
POSTGRES_USER=fyren
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ─── Redis ───
REDIS_PASSWORD=$REDIS_PASSWORD

# ─── Auth ───
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

# ─── Email ───
# Change to "ses", "sendgrid", or "smtp" and fill in credentials below
EMAIL_PROVIDER=console
# EMAIL_FROM=noreply@$APP_DOMAIN
# AWS_REGION=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# SENDGRID_API_KEY=
EOF
  success ".env file created"
}

# ─── Check Existing Install ───

check_existing() {
  if [ -f ".env" ]; then
    echo ""
    warn "An existing .env file was found in this directory."
    printf "  Overwrite? [y/N] "
    read -r answer
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
      info "Installation cancelled. Your existing .env was not modified."
      exit 0
    fi
    echo ""
  fi
}

# ─── Main ───

main() {
  banner

  info "Checking prerequisites..."
  check_prerequisites

  check_existing

  prompt_domain
  prompt_email

  info "Generating secrets..."
  generate_secrets
  success "Secrets generated"

  echo ""
  download_compose
  write_env

  echo ""
  info "Starting Fyren..."
  echo ""
  docker compose up -d

  echo ""
  echo -e "  ${GREEN}${BOLD}Fyren is starting up!${NC}"
  echo ""
  echo -e "  ${BOLD}Status page:${NC}  https://$APP_DOMAIN"
  echo -e "  ${BOLD}Config:${NC}       $(pwd)/.env"
  echo ""
  echo -e "  ${DIM}It may take a minute for SSL certificates to be issued.${NC}"
  echo -e "  ${DIM}View logs with: docker compose logs -f${NC}"
  echo ""
}

main
