#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
# Fyren Install Script
# https://fyren.dev
# ─────────────────────────────────────────────

COMPOSE_URL="https://raw.githubusercontent.com/fyrendev/fyren/main/docker-compose.images.yml"

# ─── Colors ───

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m' # No Color

# ─── Banner ───

banner() {
  printf '\n'
  printf '%b' "${CYAN}${BOLD}"
  printf '    ╔═╗┬ ┬┬─┐┌─┐┌┐┌\n'
  printf '    ╠╣ └┬┘├┬┘├┤ │││\n'
  printf '    ╚   ┴ ┴└─└─┘┘└┘\n'
  printf '%b' "${NC}"
  printf '  %bThe open source lighthouse for your services%b\n' "${DIM}" "${NC}"
  printf '\n'
}

# ─── Helpers ───

info() {
  printf '  %b>%b %s\n' "${CYAN}" "${NC}" "$1"
}

success() {
  printf '  %b✓%b %s\n' "${GREEN}" "${NC}" "$1"
}

warn() {
  printf '  %b!%b %s\n' "${YELLOW}" "${NC}" "$1"
}

error() {
  printf '  %b✗%b %s\n' "${RED}" "${NC}" "$1"
}

# ─── Prerequisites ───

check_prerequisites() {
  local missing=0

  for cmd in docker openssl curl; do
    if ! command -v "$cmd" &>/dev/null; then
      error "$cmd is not installed"
      missing=1
    else
      success "$cmd found"
    fi
  done

  if ! docker compose version &>/dev/null; then
    error "docker compose plugin is not installed"
    missing=1
  else
    success "docker compose found"
  fi

  if [ "$missing" -eq 1 ]; then
    echo ""
    error "Please install the missing prerequisites and try again."
    exit 1
  fi
}

# ─── Prompts ───

prompt_domain() {
  while true; do
    printf '\n'
    printf '  %bDomain%b\n' "${BOLD}" "${NC}"
    printf '  %bWhere will Fyren be hosted? (e.g. status.example.com)%b\n' "${DIM}" "${NC}"
    printf "  > "
    read -r APP_DOMAIN </dev/tty

    # Strip protocol prefix if provided
    APP_DOMAIN="${APP_DOMAIN#http://}"
    APP_DOMAIN="${APP_DOMAIN#https://}"
    # Strip trailing slash
    APP_DOMAIN="${APP_DOMAIN%/}"

    if [ -z "$APP_DOMAIN" ]; then
      warn "Domain cannot be empty"
      continue
    fi

    if [[ "$APP_DOMAIN" == *" "* ]]; then
      warn "Domain cannot contain spaces"
      continue
    fi

    if [[ ! "$APP_DOMAIN" == *.* ]]; then
      warn "Please enter a valid domain (e.g. status.example.com)"
      continue
    fi

    break
  done
}

prompt_email() {
  while true; do
    printf '\n'
    printf '  %bACME Email%b\n' "${BOLD}" "${NC}"
    printf '  %bEmail for Let'\''s Encrypt SSL certificates%b\n' "${DIM}" "${NC}"
    printf "  > "
    read -r ACME_EMAIL </dev/tty

    if [ -z "$ACME_EMAIL" ]; then
      warn "Email cannot be empty"
      continue
    fi

    if [[ ! "$ACME_EMAIL" == *@*.* ]]; then
      warn "Please enter a valid email address"
      continue
    fi

    break
  done
}

# ─── Generate Secrets ───

generate_secrets() {
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  REDIS_PASSWORD=$(openssl rand -hex 16)
  BETTER_AUTH_SECRET=$(openssl rand -base64 32)
}

# ─── Download Compose File ───

download_compose() {
  info "Downloading docker-compose.yml..."
  if ! curl -fsSL "$COMPOSE_URL" -o docker-compose.yml; then
    error "Failed to download docker-compose.yml"
    exit 1
  fi
  success "docker-compose.yml downloaded"
}

# ─── Write .env ───

write_env() {
  cat > .env <<EOF
# Fyren Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ─── Domain ───
APP_DOMAIN=$APP_DOMAIN
APP_URL=https://$APP_DOMAIN
ACME_EMAIL=$ACME_EMAIL

# ─── Database ───
POSTGRES_DB=fyren
POSTGRES_USER=fyren
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ─── Redis ───
REDIS_PASSWORD=$REDIS_PASSWORD

# ─── Auth ───
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

# ─── Email ───
# Change to "ses", "sendgrid", or "smtp" and fill in credentials below
EMAIL_PROVIDER=console
# EMAIL_FROM=noreply@$APP_DOMAIN
# AWS_REGION=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# SENDGRID_API_KEY=
EOF
  success ".env file created"
}

# ─── Check Existing Install ───

check_existing() {
  if [ -f ".env" ]; then
    printf '\n'
    warn "An existing .env file was found in this directory."
    printf "  Overwrite? [y/N] "
    read -r answer </dev/tty
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
      info "Installation cancelled. Your existing .env was not modified."
      exit 0
    fi
    printf '\n'
  fi
}

# ─── Main ───

main() {
  banner

  info "Checking prerequisites..."
  check_prerequisites

  check_existing

  prompt_domain
  prompt_email

  info "Generating secrets..."
  generate_secrets
  success "Secrets generated"

  printf '\n'
  download_compose
  write_env

  printf '\n'
  info "Starting Fyren..."
  printf '\n'
  docker compose up -d

  printf '\n'
  printf '  %b%bFyren is starting up!%b\n' "${GREEN}" "${BOLD}" "${NC}"
  printf '\n'
  printf '  %bStatus page:%b  https://%s\n' "${BOLD}" "${NC}" "$APP_DOMAIN"
  printf '  %bConfig:%b       %s/.env\n' "${BOLD}" "${NC}" "$(pwd)"
  printf '\n'
  printf '  %bIt may take a minute for SSL certificates to be issued.%b\n' "${DIM}" "${NC}"
  printf '  %bView logs with: docker compose logs -f%b\n' "${DIM}" "${NC}"
  printf '\n'
}

main
