#!/usr/bin/env bash
# ─────────────────────────────────────────────
# Tests for install.sh
# Run with: bash install.test.sh
# ─────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PASS=0
FAIL=0

# ─── Helpers ───

pass() {
  PASS=$((PASS + 1))
  echo -e "  \033[0;32m✓\033[0m $1"
}

fail() {
  FAIL=$((FAIL + 1))
  echo -e "  \033[0;31m✗\033[0m $1"
}

assert_eq() {
  local desc="$1" expected="$2" actual="$3"
  if [ "$expected" = "$actual" ]; then
    pass "$desc"
  else
    fail "$desc (expected '$expected', got '$actual')"
  fi
}

assert_contains() {
  local desc="$1" haystack="$2" needle="$3"
  if echo "$haystack" | grep -qF "$needle"; then
    pass "$desc"
  else
    fail "$desc (expected to contain '$needle')"
  fi
}

assert_not_contains() {
  local desc="$1" haystack="$2" needle="$3"
  if ! echo "$haystack" | grep -qF "$needle"; then
    pass "$desc"
  else
    fail "$desc (expected NOT to contain '$needle')"
  fi
}

assert_file_exists() {
  local desc="$1" path="$2"
  if [ -f "$path" ]; then
    pass "$desc"
  else
    fail "$desc (file not found: $path)"
  fi
}

# ─── Setup ───

TMPDIR_BASE=$(mktemp -d)
cleanup() { rm -rf "$TMPDIR_BASE"; }
trap cleanup EXIT

echo ""
echo "Running install.sh tests..."
echo ""

# ─── Test: Script is valid bash ───

if bash -n "$SCRIPT_DIR/install.sh" 2>/dev/null; then
  pass "install.sh has valid bash syntax"
else
  fail "install.sh has invalid bash syntax"
fi

# ─── Test: Script is executable ───

if [ -x "$SCRIPT_DIR/install.sh" ]; then
  pass "install.sh is executable"
else
  fail "install.sh is not executable"
fi

# ─── Test: Secret generation produces expected lengths ───

PG_PASS=$(openssl rand -hex 16)
assert_eq "POSTGRES_PASSWORD is 32 chars" "32" "${#PG_PASS}"

REDIS_PASS=$(openssl rand -hex 16)
assert_eq "REDIS_PASSWORD is 32 chars" "32" "${#REDIS_PASS}"

AUTH_SECRET=$(openssl rand -base64 32)
if [ "${#AUTH_SECRET}" -ge 40 ]; then
  pass "BETTER_AUTH_SECRET is long enough (${#AUTH_SECRET} chars)"
else
  fail "BETTER_AUTH_SECRET is too short (${#AUTH_SECRET} chars)"
fi

# ─── Test: .env generation ───

WORKDIR="$TMPDIR_BASE/env-test"
mkdir -p "$WORKDIR"
cd "$WORKDIR"

# Simulate the write_env function
APP_DOMAIN="status.example.com"
ACME_EMAIL="admin@example.com"
POSTGRES_PASSWORD="abc123def456ghi789jkl012mno345pq"
REDIS_PASSWORD="pq345mno012jkl789ghi456def123abc"
BETTER_AUTH_SECRET="dGVzdHNlY3JldGJhc2U2NHZhbHVlMTIzNDU2Nzg5MA=="

cat > .env <<EOF
# Fyren Configuration
# Generated by install.sh

# ─── Domain ───
APP_DOMAIN=$APP_DOMAIN
APP_URL=https://$APP_DOMAIN
ACME_EMAIL=$ACME_EMAIL

# ─── Database ───
POSTGRES_DB=fyren
POSTGRES_USER=fyren
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ─── Redis ───
REDIS_PASSWORD=$REDIS_PASSWORD

# ─── Auth ───
BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET

# ─── Email ───
EMAIL_PROVIDER=console
EOF

assert_file_exists ".env file is created" "$WORKDIR/.env"

ENV_CONTENT=$(cat "$WORKDIR/.env")
assert_contains ".env contains APP_DOMAIN" "$ENV_CONTENT" "APP_DOMAIN=status.example.com"
assert_contains ".env contains APP_URL" "$ENV_CONTENT" "APP_URL=https://status.example.com"
assert_contains ".env contains ACME_EMAIL" "$ENV_CONTENT" "ACME_EMAIL=admin@example.com"
assert_contains ".env contains POSTGRES_DB default" "$ENV_CONTENT" "POSTGRES_DB=fyren"
assert_contains ".env contains POSTGRES_USER default" "$ENV_CONTENT" "POSTGRES_USER=fyren"
assert_contains ".env contains POSTGRES_PASSWORD" "$ENV_CONTENT" "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
assert_contains ".env contains REDIS_PASSWORD" "$ENV_CONTENT" "REDIS_PASSWORD=$REDIS_PASSWORD"
assert_contains ".env contains BETTER_AUTH_SECRET" "$ENV_CONTENT" "BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET"
assert_contains ".env contains EMAIL_PROVIDER default" "$ENV_CONTENT" "EMAIL_PROVIDER=console"

# ─── Test: Domain validation patterns ───

# Strip protocol
domain="https://status.example.com"
domain="${domain#http://}"
domain="${domain#https://}"
domain="${domain%/}"
assert_eq "strips https:// prefix" "status.example.com" "$domain"

domain="http://status.example.com"
domain="${domain#http://}"
domain="${domain#https://}"
domain="${domain%/}"
assert_eq "strips http:// prefix" "status.example.com" "$domain"

domain="status.example.com/"
domain="${domain#http://}"
domain="${domain#https://}"
domain="${domain%/}"
assert_eq "strips trailing slash" "status.example.com" "$domain"

# Domain has a dot
domain="status.example.com"
if [[ "$domain" == *.* ]]; then
  pass "valid domain passes dot check"
else
  fail "valid domain fails dot check"
fi

domain="localhost"
if [[ "$domain" == *.* ]]; then
  fail "localhost should fail dot check"
else
  pass "localhost correctly fails dot check"
fi

# ─── Test: Email validation pattern ───

email="admin@example.com"
if [[ "$email" == *@*.* ]]; then
  pass "valid email passes check"
else
  fail "valid email fails check"
fi

email="notanemail"
if [[ "$email" == *@*.* ]]; then
  fail "invalid email should fail check"
else
  pass "invalid email correctly fails check"
fi

email="missing@domain"
if [[ "$email" == *@*.* ]]; then
  fail "email without TLD should fail check"
else
  pass "email without TLD correctly fails check"
fi

# ─── Test: Prerequisite check function works ───

# We can't easily test the full function without mocking, but we can verify
# the commands it checks for exist on this machine
for cmd in openssl curl; do
  if command -v "$cmd" &>/dev/null; then
    pass "prerequisite '$cmd' is available on test machine"
  else
    fail "prerequisite '$cmd' is not available on test machine"
  fi
done

# ─── Test: Compose URL is valid ───

COMPOSE_URL="https://raw.githubusercontent.com/fyrendev/fyren/main/docker-compose.images.yml"
if [[ "$COMPOSE_URL" == https://* ]]; then
  pass "compose URL uses HTTPS"
else
  fail "compose URL does not use HTTPS"
fi

if [[ "$COMPOSE_URL" == *docker-compose.images.yml ]]; then
  pass "compose URL points to docker-compose.images.yml"
else
  fail "compose URL does not point to docker-compose.images.yml"
fi

# ─── Summary ───

echo ""
TOTAL=$((PASS + FAIL))
echo "  $TOTAL tests: $PASS passed, $FAIL failed"
echo ""

if [ "$FAIL" -gt 0 ]; then
  exit 1
fi
